---
openapi: 3.0.1
info:
  title: Centralized Metadata Repository
  version: v1
paths:
  "/records/{record_id}/local_notes":
    get:
      summary: show local note fields
      tags:
      - local_notes
      description: This web service retrieves local note field(s) (cm_local_note)
        associated with a Centralized Metadata Repository record, as a JSON array.
      parameters:
      - name: record_id
        in: path
        description: The id of the Centralized Metadata Repository record
        required: true
        schema:
          type: string
      responses:
        '422':
          description: unsuccessful
        '200':
          description: successful
          content:
            application/json:
              examples:
                no-notes:
                  value: "[]"
                a-note:
                  value:
                  - id: 1
                    cm_local_note: foo
                some-notes:
                  value:
                  - id: 1
                    cm_local_note: foo
                  - id: 2
                    cm_local_note: bar
    post:
      summary: create local note fields
      tags:
      - local_notes
      parameters:
      - name: record_id
        in: path
        description: The id of the Centralized Metadata Repository record
        required: true
        schema:
          type: string
      description: This web service creates local note field(s) (cm_local_note) for
        a Centralized Metadata Repository record.
      responses:
        '422':
          description: unsuccessful
        '200':
          description: successful
          content:
            application/json:
              examples:
                some-notes:
                  value:
                  - id: 1
                    cm_local_note: foo
                  - id: 2
                    cm_local_note: bar
                a-note:
                  value:
                  - id: 1
                    cm_local_note: foo
              schema:
                "$ref": "#/components/schemas/LocalNotes"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/LocalNote"
            examples:
              default:
                summary: create local note fields
                value:
                  cm_local_note: Hello World
        required: true
  "/records/{record_id}/local_notes/{note_id}":
    get:
      summary: show local note field
      tags:
      - local_notes
      parameters:
      - name: record_id
        in: path
        description: The id of the Centralized Metadata Repository record
        required: true
        schema:
          type: string
      - name: note_id
        in: path
        description: The id of the local note field
        required: true
        schema:
          type: string
      description: This web service retrieves the value of a local note field (cm_local_note)
        from a Centralized Metadata Repository record. .
      responses:
        '422':
          description: unsuccessful
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: string
    put:
      summary: update local note field
      tags:
      - local_notes
      parameters:
      - name: record_id
        in: path
        description: The id of the Centralized Metadata Repository record
        required: true
        schema:
          type: string
      - name: note_id
        in: path
        description: The id of the local note field
        required: true
        schema:
          type: string
      description: 'This web service updates a local note field (cm_local_note) in
        a Centralized Metadata Repository record. '
      responses:
        '422':
          description: unsuccessful
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/LocalNote"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/LocalNote"
            examples:
              default:
                summary: update local note field
                value:
                  cm_local_note: Hello World
        required: true
    delete:
      summary: delete local note field
      tags:
      - local_notes
      parameters:
      - name: record_id
        in: path
        description: The id of the Centralized Metadata Repository record
        required: true
        schema:
          type: string
      - name: note_id
        in: path
        description: The id of the local note field
        required: true
        schema:
          type: string
      description: This web service deletes a local note field (cm_local_note) from
        a Centralized Metadata Repository record.
      responses:
        '422':
          description: unsuccessful
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: string
  "/records/{record_id}/local_var_labels":
    get:
      summary: show local variant label fields
      tags:
      - local_var_labels
      description: This web service retrieves the local variant label fields (cm_local_var_label)
        associated to a Centralized Metadata Repository record, formatted as a JSON
        array.
      parameters:
      - name: record_id
        in: path
        description: The id of the Centralized Metadata Repository record
        required: true
        schema:
          type: string
      responses:
        '422':
          description: unsuccessful
        '200':
          description: successful
          content:
            application/json:
              examples:
                no-var_labels:
                  value: "[]"
                a-var_label:
                  value:
                  - id: 1
                    cm_local_var_label: foo
                some-var_labels:
                  value:
                  - id: 1
                    cm_local_var_label: foo
                  - id: 2
                    cm_local_var_label: bar
    post:
      summary: create local variant label fields
      tags:
      - local_var_labels
      parameters:
      - name: record_id
        in: path
        description: The id of the Centralized Metadata Repository record
        required: true
        schema:
          type: string
      description: The web service creates local variant label field(s) (cm_local_var_label)
        for a Centralized Metadata Repository record.
      responses:
        '422':
          description: unsuccessful
        '200':
          description: successful
          content:
            application/json:
              examples:
                some-var_labels:
                  value:
                  - id: 1
                    cm_local_var_label: foo
                  - id: 2
                    cm_local_var_label: bar
                a-var_label:
                  value:
                  - id: 1
                    cm_local_var_label: foo
              schema:
                "$ref": "#/components/schemas/LocalVarLabels"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/LocalVarLabel"
            examples:
              default:
                summary: create local variant label fields
                value:
                  cm_local_var_label: Hello World
        required: true
  "/records/{record_id}/local_var_labels/{var_label_id}":
    get:
      summary: show local variant label field
      tags:
      - local_var_labels
      parameters:
      - name: record_id
        in: path
        description: The id of the Centralized Metadata Repository record
        required: true
        schema:
          type: string
      - name: var_label_id
        in: path
        description: The id of the local variant label field
        required: true
        schema:
          type: string
      description: This web service retrieves the value of a local variant label field
        (cm_local_var_label) in a Centralized Metadata Repository record.
      responses:
        '422':
          description: unsuccessful
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: string
    put:
      summary: update local variant label field
      tags:
      - local_var_labels
      parameters:
      - name: record_id
        in: path
        description: The id of the Centralized Metadata Repository record
        required: true
        schema:
          type: string
      - name: var_label_id
        in: path
        description: The id of the local variant label field
        required: true
        schema:
          type: string
      description: This web service updates the value of a local variant label field
        (cm_local_var_label) in a Centralized Metadata Repository record.
      responses:
        '422':
          description: unsuccessful
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/LocalVarLabel"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/LocalVarLabel"
            examples:
              default:
                summary: update local variant label field
                value:
                  cm_local_var_label: Hello World
        required: true
    delete:
      summary: delete local variant label field
      tags:
      - local_var_labels
      parameters:
      - name: record_id
        in: path
        description: The id of the Centralized Metadata Repository record
        required: true
        schema:
          type: string
      - name: var_label_id
        in: path
        description: The id of the local variant label field
        required: true
        schema:
          type: string
      description: This web service deletes a local variant label field (cm_local_var_label)
        in a Centralized Metadata Repository record.
      responses:
        '422':
          description: unsuccessful
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: string
  "/marc_file/delete":
    post:
      summary: delete records using MARC file
      tags:
      - marc_file
      parameters: []
      description: This web service deletes records in the Centralized Metadata Repository
        that match records from the posted MARC file.
      responses:
        '422':
          description: unsuccessful
        '200':
          description: successful
          headers:
            X-CM-Records-Processed-Count:
              schema:
                type: integer
              description: The number of records processed.
            X-CM-Total-Records-Count:
              schema:
                type: integer
              description: The total number of records int the database.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Records"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                marc_file:
                  type: string
                  format: binary
                kind:
                  type: string
  "/marc_file/ids":
    post:
      summary: retrieve record ids from MARC file
      tags:
      - marc_file
      parameters: []
      description: This web service processes a posted MARC file and returns the ids
        of the records defined in the MARC file.
      responses:
        '422':
          description: unsuccessful
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                marc_file:
                  type: string
                  format: binary
                kind:
                  type: string
  "/records":
    get:
      summary: list records
      tags:
      - records
      description: This web service retrieves a list of the Centralized Metadata Repository
        records in a JSON format. The pagination default is set to return 25 records
        at a time. If you would like to change this, add the parameter per_page=number_desired
        to the query parameters. This service also takes a 'page' parameter.
      parameters:
      - name: page
        in: query
        description: page number
        required: false
        schema:
          type: string
      - name: per_page
        in: query
        description: number of records per page
        required: false
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Records"
    post:
      summary: create records
      tags:
      - records
      parameters: []
      description: "This web service creates Centralized Metadata Repository records
        from a MARC binary file. There are two methods for adding records. \n      Using
        a curl statement: curl -F 'marc_file=@spec/fixtures/marc/louis_armstrong.mrc'
        https://centralized-metadata-qa.k8s.temple.edu\n      Ingest with a rake task:
        rake db:ingest[spec/fixtures/marc]."
      responses:
        '200':
          description: successful
          headers:
            X-CM-Records-Processed-Count:
              schema:
                type: integer
              description: The number of records processed.
            X-CM-Total-Records-Count:
              schema:
                type: integer
              description: The total number of records int the database.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Records"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                marc_file:
                  type: string
                  format: binary
                kind:
                  type: string
  "/records/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show record
      tags:
      - records
      description: This web service retreives a Centralized Metadata Repository record
        in a JSON format.
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Record"
    put:
      summary: update record
      tags:
      - records
      description: This web service updates a Centralized Metadata Repository record
        as an entire resource from a MARC binary file.
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: unsuccessful
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Record"
            examples:
              example1:
                summary: update record
                value:
                  cm_id:
                  - fst01423682
                  cm_pref_label:
                  - Abbreviations of titles
                  cm_source_vocab:
                  - lcgft
                  cm_import_method:
                  - MARC binary
                  cm_filename:
                  - TEUM_CNS_GNR.mrc
                  cm_type:
                  - genre
        required: true
        description: The value section of the Centralized Metadata Repository record
    patch:
      summary: update record
      tags:
      - records
      description: This web service updates a Centralized Metadata Repository record
        with partial data, restricted to the specific fields. Use if you want to execute
        a partial update of a record.
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: unsuccessful
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Record"
            examples:
              example1:
                summary: update record
                value:
                  cm_id:
                  - fst01423682
                  cm_pref_label:
                  - Abbreviations of titles
                  cm_source_vocab:
                  - lcgft
                  cm_import_method:
                  - MARC binary
                  cm_filename:
                  - TEUM_CNS_GNR.mrc
                  cm_type:
                  - genre
        required: true
        description: The value section of the Centralized Metadata Repository record
    delete:
      summary: delete record
      tags:
      - records
      description: This web service deletes a Centralized Metadata Repository record.
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Record"
servers:
- url: https://centralized-metadata-qa.k8s.temple.edu
- url: http://localhost:3000
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: centralized-metadata-qa.k8s.temple.edu
components:
  schemas:
    Record:
      type: object
      properties:
        cm_id:
          type: array
          items:
            type: string
        cm_pref_label:
          type: array
          items:
            type: string
        cm_var_label:
          type: array
          items:
            type: string
        cm_source_vocab:
          type: array
          items:
            type: string
        cm_import_method:
          type: array
          items:
            type: string
        cm_filename:
          type: array
          items:
            type: string
        cm_type:
          type: array
          items:
            type: string
        cm_see_also:
          type: array
          items:
            type: string
        cm_lc_class:
          type: array
          items:
            type: string
        cm_narrower_term:
          type: array
          items:
            type: string
        cm_broader_term:
          type: array
          items:
            type: string
        cm_use_subject:
          type: array
          items:
            type: string
        cm_undiff_name:
          type: array
          items:
            type: string
        cm_birth_date:
          type: array
          items:
            type: string
        cm_death_date:
          type: array
          items:
            type: string
        cm_establishment_date:
          type: array
          items:
            type: string
        cm_termination_date:
          type: array
          items:
            type: string
        cm_start_period:
          type: array
          items:
            type: string
        cm_end_period:
          type: array
          items:
            type: string
        cm_place_of_birth:
          type: array
          items:
            type: string
        cm_place_of_death:
          type: array
          items:
            type: string
        cm_associated_country:
          type: array
          items:
            type: string
        cm_residencehq:
          type: array
          items:
            type: string
        cm_other_associated_place:
          type: array
          items:
            type: string
        cm_field_activity:
          type: array
          items:
            type: string
        cm_associated_group:
          type: array
          items:
            type: string
        cm_occupation:
          type: array
          items:
            type: string
        cm_gender:
          type: array
          items:
            type: string
        cm_type_family:
          type: array
          items:
            type: string
        cm_prom_member:
          type: array
          items:
            type: string
        cm_heredity_title:
          type: array
          items:
            type: string
        cm_associated_language:
          type: array
          items:
            type: string
        cm_fuller_name:
          type: array
          items:
            type: string
        cm_type_corporate_body:
          type: array
          items:
            type: string
        cm_type_jurisdiction:
          type: array
          items:
            type: string
        cm_other_designation:
          type: array
          items:
            type: string
        cm_title_person:
          type: array
          items:
            type: string
        cm_content_type:
          type: array
          items:
            type: string
        cm_form_work:
          type: array
          items:
            type: string
        cm_medium_performance:
          type: array
          items:
            type: string
        cm_solist:
          type: array
          items:
            type: string
        cm_doubling_instrument:
          type: array
          items:
            type: string
        cm_alternative_medium_performance:
          type: array
          items:
            type: string
        cm_original_key:
          type: array
          items:
            type: string
        cm_transposed_key:
          type: array
          items:
            type: string
        cm_music_num_designation:
          type: array
          items:
            type: string
        cm_audience_characteristics:
          type: array
          items:
            type: string
        cm_characteristics:
          type: array
          items:
            type: string
        cm_work_time_creation:
          type: array
          items:
            type: string
        cm_aggwork_time_creation:
          type: array
          items:
            type: string
        cm_work_language:
          type: array
          items:
            type: string
        cm_notmusic_format:
          type: array
          items:
            type: string
        cm_beginning_date_created:
          type: array
          items:
            type: string
        cm_ending_date_created:
          type: array
          items:
            type: string
        cm_place_origin_work:
          type: array
          items:
            type: string
        cm_series_pubdates:
          type: array
          items:
            type: string
        cm_series_num_peculiar:
          type: array
          items:
            type: string
        cm_series_num_ex:
          type: array
          items:
            type: string
        cm_series_placepub:
          type: array
          items:
            type: string
        cm_series_analysis:
          type: array
          items:
            type: string
        cm_series_tracing_practice:
          type: array
          items:
            type: string
        cm_series_classificaton_practice:
          type: array
          items:
            type: string
        cm_created_at:
          type: string
          format: date
        cm_updated_at:
          type: string
          format: date
        local_metadatum:
          "$ref": "#/components/schemas/LocalMetadatum"
          x-nullable: true
      required:
      - cm_id
    Records:
      type: array
      items:
        "$ref": "#/components/schemas/Record"
    LocalNote:
      type: object
      required:
      - cm_local_note
      properties:
        id:
          type: integer
        cm_local_note:
          type: string
    LocalNotes:
      type: array
      items:
        "$ref": "#/components/schemas/LocalNote"
    LocalVarLabel:
      type: object
      required:
      - cm_local_var_label
      properties:
        id:
          type: integer
        cm_local_var_label:
          type: string
    LocalVarLabels:
      type: array
      items:
        "$ref": "#/components/schemas/LocalVarLabel"
    LocalMetadatum:
      type: object
      properties:
        local_notes:
          type: array
          "$ref": "#/components/schemas/LocalNotes"
        local_var_labels:
          type: array
          "$ref": "#/components/schemas/LocalVarLabels"
